Fix warning emitted by werkzeug
closeio/flask-tracking pull request #2
Opened 2019-04-17 06:11 UTC by mpessas

See https://github.com/pallets/werkzeug/blob/0.10.4/werkzeug/datastructures.py#L1178-L1183.

2019-04-17 13:04 UTC, thomasst requested changes

2019-04-17 13:04 UTC, thomasst commented on flask_tracking/__init__.py
> +                response_headers=response.headers.to_wsgi_list(response.charset),
But `to_wsgi_list` doesn't take a charset argument here: https://github.com/pallets/werkzeug/blob/0.10.4/werkzeug/datastructures.py#L1185

2019-04-17 13:36 UTC, thomasst approved these changes
Looks good, and ideally this would have to be tested with different response encodings (but it's no worse than what we currently have).

2019-04-19 05:35 UTC, mpessas commented
Well, given the code already drops the charset, the code will behave exactly as how it behaves now.

2019-04-19 06:43 UTC, merged